name: Open Machine Build

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '11.3.Rel1' # <-- The version used by the STM32CLT install

    - name: Make Blinky
      run: make all
      working-directory: ./code/examples/blinky/blinky_h743

    - name: Create Distribution Directory
      run: |
        mkdir release        
        cp ./code/examples/blinky/blinky_h743/build/blinky_h743.bin ./release/blinky_h743.bin
        cp ./code/examples/blinky/blinky_h743/build/blinky_h743.hex ./release/blinky_h743.hex
        cp ./code/examples/blinky/blinky_h743/build/blinky_h743.elf ./release/blinky_h743.elf
        echo ${{ github.sha }} > ./release/github_sha.txt

    - uses: actions/upload-artifact@v3
      with:
        name: Open Machine Release
        path: |
          ./release
    
